#!/bin/bash
#Created By Artydude alias Artoine

echo "This is a simple file encrypter/decrypter"
echo "-----------------------------------------"
echo " "

loop=0
loop2=0
loop3=0

while [ $loop -eq 0 ]
do
		loop=1
		echo "1 Encrypt"
		echo "2 Decrypt"
		read -p "Please choose one of these options: " REPLY

		if [[ $REPLY -ne 1 ]] && [[ $REPLY -ne 2 ]];
		then
			echo "There is only option 1 and option 2"
			loop=0
		else

		while [ $loop3 -eq 0 ]
		do
				loop3=1
				loop2=0
				read -p  "Please enter the path: " path

			while [ $loop2 -eq 0 ]
			do
					loop2=1
					read -p  "Please enter the filename: " file

					if [ -f "$path""$file" ]
					then
						echo "File exists"
						cd $path

						if [ $REPLY -eq 1 ]
						then
							echo "You have selected encryption"
							gpg -c $file
							echo "File has been encrypted"
						fi

						if [ $REPLY -eq 2 ]
						then
							echo "You have selected decryption"
							gpg -d $file
							echo "File has been decrypted"
						fi

					else
						if [ -d $path ]
						then
							echo "Path exists"
							echo "Filename must be wrong"
							loop2=0
						else
							echo "Path not founded"
							loop3=0
						fi
					fi
			done
		done
		fi
done
